id: AC77C868B
title: 'Vajra Net: The Ancillary Preliminary and Concluding Practices for the Three
  Drops, the Guru Yogas for Venerable Marpa, Mila, and Gampopa'
type: translation
pechas:
- I62564514
- I88BB4BB1
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:55:58.070116
  last_modified_at: 2023-01-04 11:55:58.070127
  collections:
  - Gampopa Series
  - Works of Tibetan Masters
alignment_to_base:
  I62564514/1DF7: E333
  I88BB4BB1/B2BD: E333
